Removing Pydantic Table from the Schema
getmomentum/momentum-core pull request #30
Opened 2024-07-05 22:01 UTC by cash1998

- [x] Removed the logic where pydantic details are stored in postgres
- [x] Added logic to fetch the Pydantic class node details from neo4j
- [x] Logic to fetch classes from github repos
- [x] Deleted pydantic table   
- [x] Tested on local & docker

2024-07-05 22:47 UTC, dhirenmathur reviewed
Are duplicate class names handled? 
Are multiple class imports handled?

2024-07-05 22:48 UTC, dhirenmathur requested changes
Add error handling in neo4j queries

2024-07-06 03:39 UTC, cash1998 commented
> Are duplicate class names handled? 
No, the older code also did not tackle this issue, pondered a lot and seemed this was the best solution as for now

> Are multiple class imports handled?
Yes, it is being handled.

2024-07-06 14:25 UTC, dhirenmathur requested changes

2024-07-06 14:25 UTC, dhirenmathur commented on server/utils/parse_helper.py
> -    EndpointManager(directory).delete_pydantic_entries(project_id, user_id)
pleaase delete pydantic reference frommknowledge graph file as well

2024-07-07 02:53 UTC, dhirenmathur submitted a review, later dismissed

2024-07-10 07:36 UTC, dhirenmathur submitted a review, later dismissed

2024-07-10 08:03 UTC, dhirenmathur approved these changes

2024-07-10 08:03 UTC, merged