changes to seperate kg, add submodule, integrate celery
getmomentum/momentum-core pull request #31
Opened 2024-07-06 01:30 UTC by vineetshar

- [ ] Tested on local & docker
- [ ] Documentation Updated
- [ ] Attached required context / screenshot

2024-07-06 13:58 UTC, dhirenmathur requested changes

2024-07-06 13:58 UTC, dhirenmathur commented on server/test_agent/tools.py
> +      response = requests.post(kg_query_url, json=data, headers=headers)
is this async?

2024-07-10 00:20 UTC, vineetshar commented on server/api/routers/auth.py
>  @auth_router.post("/login")
using this to generate token in dev.

2024-07-10 00:28 UTC, dhirenmathur approved these changes

2024-07-10 00:29 UTC, merged