Picking up firebase env from .env file
getmomentum/momentum-core pull request #46
Opened 2024-07-17 04:35 UTC by vineetshar

- [x] Tested on local & docker
- [ ] Documentation Updated
- [ ] Attached required context / screenshot

2024-07-17 04:37 UTC, cash1998 approved these changes

2024-07-17 04:37 UTC, merged

2024-07-17 04:39 UTC, dhirenmathur requested changes

2024-07-17 04:39 UTC, dhirenmathur commented on server/firebase_setup.py
> +    print("Loading service account")
Remove print statement

2024-07-17 04:39 UTC, dhirenmathur commented on server/firebase_setup.py
> +            print("Loaded Firebase credentials from environment variable.")
Print statement

2024-07-17 04:39 UTC, dhirenmathur commented on server/firebase_setup.py
> +            print("Loaded Firebase credentials from local file as fallback.")
Print

2024-07-17 04:39 UTC, dhirenmathur commented on server/firebase_setup.py
> +        print("Loaded Firebase credentials from local file.")
One more

2026-03-11 10:04 UTC, Harigithub11 commented
This pull request was merged before a formal code review and approval process was established. The change was reviewed after the merge and accepted as a known exception. The repository now enforces pull request approvals through branch protection rules to prevent this from happening in the future.