Adding logic to delete projects
getmomentum/momentum-core pull request #9
Opened 2024-06-28 01:29 UTC by cash1998

- [x] Added a column called "is_deleted" to denote a project's soft delete
- [x] Removed directory column's unique constraint to allow for a reparse for a project that has been deleted
- [x] Updated exiswting project fetches to fetch only non-deleted projects
- [x] Testing on local for these changes

2024-07-03 06:23 UTC, dhirenmathur requested changes

2024-07-04 06:11 UTC, cash1998 commented on server/projects.py
>              )
This is to increase readability- a line shoudn't have more than 120 characters.

2024-07-04 18:48 UTC, dhirenmathur commented on server/projects.py
>              )
no i meant use multiline string

2024-07-05 21:02 UTC, dhirenmathur requested changes

2024-07-05 21:03 UTC, dhirenmathur commented on server/projects.py
> +            cursor.execute(f"SELECT id, directory, is_default FROM projects {self.is_deleted_condition}")
also coincidently was reading something and found this
<img width="491" alt="image" src="https://github.com/getmomentum/momentum-core/assets/19893222/f414f0cf-41f6-4cf8-8a8b-bd07af06d6c7">

2024-07-06 03:56 UTC, cash1998 commented on server/projects.py
> +            cursor.execute(f"SELECT id, directory, is_default FROM projects {self.is_deleted_condition}")
The sql injection will happen only if the string is a variable, and is an input from some place
In this case it's a hardcoded value

2024-07-10 05:57 UTC, cash1998 commented on server/routers/webhook.py
> +        if repository_field in payload:
repository_field is - 
    "added": "repositories_added",
        "created": "repositories"
        "created": "repositories",
        "removed": "repositories_removed"
    }.get(payload["action"], None)
    
    fetching the value from the dictionary on the basis of "action" value

2024-07-10 07:40 UTC, dhirenmathur approved these changes

2024-07-10 08:05 UTC, merged